name: Custom Workflow

on: 
  push:
    branches: [develop]

jobs:
  custom-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Install dependencies and Run test 
        working-directory: sample-app
        run: |
          npm install
          npm test 
        
